### ISSUE TITLE
java.lang.NoClassDefFoundError: uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder

### ISSUE THREAD

**Issue by kelvinofula** [sjwall/MaterialTapTargetPrompt#120]
06-24 14:41:27.994 20376-20376/com.coretec.msacco E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder
        at com.coretec.msacco.Dashboard.DashboardMain.initializeDrawer(DashboardMain.java:333)
        at com.coretec.msacco.Dashboard.DashboardMain.onCreate(DashboardMain.java:179)
        at android.app.Activity.performCreate(Activity.java:4466)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
        at android.app.ActivityThread.access$600(ActivityThread.java:123)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4424)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by kelvinofula** [comment]
The issue is only experienced on android versions below 5.0, that is 4.0 to 4.4

**Comment by sjwall** [comment]
I have briefly researched this and it looks like a configuration issue with your instrumentation tests. Not sure exactly what yet but I will give it a go at implementing some in the library (hopefully by the end of the week) so that you can see an example that works

**Comment by sjwall** [comment]
I have added an example instrumentation test to the sample app in 2098f2a
You may need to also add a instrumentation tests import for the library in `build.gradle` like so:

```groovy
androidTestImplementation 'uk.co.samuelwall:material-tap-target-prompt:2.9.0'
```
Hope that this helps

**Comment by kelvinofula** [comment]
I found out the problem was due to multidex. During build the library could
not be stored in the primary dex hence the crashing while running on
android versions below 5.
Weird enough I just moved the implementation line upwards in the code as
opposed to below the code where I had placed it and it worked. But thanks
for the response, I really appreciate.
