### ISSUE TITLE
java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method

### ISSUE THREAD

**Issue by pesjak** [sjwall/MaterialTapTargetPrompt#167]
**Describe the bug**
Crashes when trying to show or create the MaterialTapTargetPrompt

**To Reproduce**
Steps to reproduce the behaviour including how the prompt builder is created:
Crashes onCreate.

**Stack trace**
 java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
        at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt.<init>(MaterialTapTargetPrompt.java:158)
        at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt.createDefault(MaterialTapTargetPrompt.java:719)
        at uk.co.samuelwall.materialtaptargetprompt.extras.PromptOptions.create(PromptOptions.java:1498)
        at uk.co.samuelwall.materialtaptargetprompt.extras.PromptOptions.show(PromptOptions.java:1560)
        at com.views.fragments.ACStartRentalFragment.showQuickStart(ACStartRentalFragment.kt:83)
        at com.views.fragments.ACStartRentalFragment.onViewCreated(ACStartRentalFragment.kt:53)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1470)
        at android.app.Activity.performStart(Activity.java:7170)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3071)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt.<init>(MaterialTapTargetPrompt.java:158) 
        at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt.createDefault(MaterialTapTargetPrompt.java:719) 
        at uk.co.samuelwall.materialtaptargetprompt.extras.PromptOptions.create(PromptOptions.java:1498) 
        at uk.co.samuelwall.materialtaptargetprompt.extras.PromptOptions.show(PromptOptions.java:1560) 
        at com.views.fragments.ACStartRentalFragment.showQuickStart(ACStartRentalFragment.kt:83) 
        at com.views.fragments.ACStartRentalFragment.onViewCreated(ACStartRentalFragment.kt:53) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439) 
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613) 
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1470) 
        at android.app.Activity.performStart(Activity.java:7170) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3071) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6898)

**Smartphone (please complete the following information):**
 - Device: One Plus 6t
 - OS: Android 9
 - Library version 3.0.0.

**Additional context**
This is inside a Fragment.
```
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setOnClickListeners()
        showQuickStart()
    }
private fun showQuickStart() {
        MaterialTapTargetPrompt.Builder(this)
                .setTarget(confirmRentalButton)
                .setPrimaryText("Novo poročanje poškodb")
                .setSecondaryText("Some text")
                .setBackButtonDismissEnabled(true)
                .setPromptBackground(RectanglePromptBackground())
                .setPromptFocal(RectanglePromptFocal())
                .show()
    }
```

**Comment by yuvraj24** [comment]
I was facing the same problem. Just enable Java 8 in your builds to function, this is what worked for me ....

app.gradle

```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by pesjak** [comment]
It worked thanks :)
