### ISSUE TITLE
NullPointerException at onAnimationEnd(MaterialTapTargetPrompt.java:529) on some devices running Android 6.0

### ISSUE THREAD

**Issue by alixwar** [sjwall/MaterialTapTargetPrompt#186]
Some crashes collected by Crashlytics:

 Android version: 6.0
 Device: LG X cam
 ```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.ValueAnimator.start()' on a null object reference
       at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$5.onAnimationUpdate(MaterialTapTargetPrompt.java:570)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:642)
       at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:589)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
       at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt.startIdleAnimations(MaterialTapTargetPrompt.java:578)
       at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$4.onAnimationEnd(MaterialTapTargetPrompt.java:529)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
       at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:603)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
```

Android version: 6.0
Device: YUNICORN

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.animation.ValueAnimator.start()' on a null object reference
uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$5.onAnimationUpdate (MaterialTapTargetPrompt.java:570)
android.animation.ValueAnimator.animateValue (ValueAnimator.java:1463)
android.animation.ValueAnimator.setCurrentFraction (ValueAnimator.java:642)
android.animation.ValueAnimator.setCurrentPlayTime (ValueAnimator.java:589)
android.animation.ValueAnimator.start (ValueAnimator.java:1106)
android.animation.ValueAnimator.start (ValueAnimator.java:1117)
uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt.startIdleAnimations (MaterialTapTargetPrompt.java:578)
uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$4.onAnimationEnd (MaterialTapTargetPrompt.java:529)
android.animation.ValueAnimator.endAnimation (ValueAnimator.java:1239)
android.animation.ValueAnimator$AnimationHandler.doAnimationFrame (ValueAnimator.java:766)
android.animation.ValueAnimator$AnimationHandler$1.run (ValueAnimator.java:801)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:894)
android.view.Choreographer.doCallbacks (Choreographer.java:696)
android.view.Choreographer.doFrame (Choreographer.java:628)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:880)
android.os.Handler.handleCallback (Handler.java:815)
android.os.Handler.dispatchMessage (Handler.java:104)
android.os.Looper.loop (Looper.java:207)
android.app.ActivityThread.main (ActivityThread.java:5692)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:905)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:766)
```

**Comment by sjwall** [comment]
Thanks for the report, looks like the animator is starting before all the variables it uses are initialised. Fix will be in the next release
