### ISSUE TITLE
Crash on OnePlus IN2021: java.lang.NullPointerException: Attempt to read from field 'boolean android.graphics.Path.isSimplePath' on a null object reference

### ISSUE THREAD

**Issue by alwa** [sjwall/MaterialTapTargetPrompt#190]
**Describe the bug**
Crash reported from Crashlytics.

**Stack trace**
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'boolean android.graphics.Path.isSimplePath' on a null object reference
       at android.graphics.BaseRecordingCanvas.drawPath(BaseRecordingCanvas.java:442)
       at uk.co.samuelwall.materialtaptargetprompt.extras.focals.CirclePromptFocal.draw(CirclePromptFocal.java:190)
       at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$PromptView.onDraw(MaterialTapTargetPrompt.java:803)
       at android.view.View.draw(View.java:22528)
       at android.view.View.updateDisplayListIfDirty(View.java:21389)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.draw(View.java:22538)
       at com.android.internal.policy.DecorView.draw(DecorView.java:812)
       at android.view.View.updateDisplayListIfDirty(View.java:21389)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4379)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4106)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3353)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2152)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8675)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
       at android.view.Choreographer.doFrame(Choreographer.java:1049)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Smartphone**
 - OnePlus IN2021
 - OS: Android 11
 - Library version: 3.0.0

**Additional context**
targetSdk=30

**Comment by sjwall** [comment]
Thanks for the report, fix will be released in next version
