### ISSUE TITLE
Getting NullPointer for showing prompt

### ISSUE THREAD

**Issue by chinmoyeedash** [sjwall/MaterialTapTargetPrompt#37]
Getting Nullpointer exception with 1.8.2 as well as 1.8.1.. Target is a menuitem in actionmode. I had to update the library as i updated my compilesdkversion to 25

 compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'com.android.support:support-v4:25.0.0'
    compile 'com.android.support:design:25.0.0'
    compile 'uk.co.samuelwall:material-tap-target-prompt:1.8.2'

I have only added this in build.gradle, not imported it as module in my project.
Code is fine as it  works perfectly with design:23.0.1 and uk.co.samuelwall:material-tap-target-prompt:1.1.4

Sending you the error message

java.lang.NullPointerException
                                                                             at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt.updateFocalCentrePosition(MaterialTapTargetPrompt.java:714)
                                                                             at uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$2.onGlobalLayout(MaterialTapTargetPrompt.java:335)
                                                                             at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:859)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2048)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1234)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:613)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:583)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
                                                                             at android.os.Handler.handleCallback(Handler.java:733)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:146)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5511)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by sjwall** [comment]
The closest I can get to replicating this is `setTarget(null)`. I have made it handle this scenario gracefully in v1.8.3. If the target view is null then `builder.create()` will return null and `builder.show()` will not show the prompt.

Check that the view you are targeting is not null. Let me know if this helps, if not I will investigate further

**Comment by chinmoyeedash** [comment]
No, As I mentioned code works perfectly with appcompat:23 and design: 23, with materialtaptarget1.1.4 which i have swapped and checked. This error comes the only when i update the build.gradle and sync

**Comment by sjwall** [comment]
Ok, I shall investigate further. 
How are you targeting the action mode item, by item id or by `getChildAt`? 
Does the null pointer exception still occur with v1.8.3?

**Comment by chinmoyeedash** [comment]
With 1.8.3 as you told it exits gracefully .. Nullpointer does not go to MaterialTapTarget.java but shows on my activity where i create taptarget on mPrompt. 

mPrompt=new MaterialTapTargetPrompt.Builder(context)
				.setTarget(findViewById(R.id.menu_next)) (have tried declaring view separately also)
				.setTargetRenderView(findViewById(R.id.menu_next))
				.setSecondaryText("---")
				.setPrimaryText("Next")
				.setTextPadding(10f)
				.setSecondaryTextColour(Color.WHITE)
				.setAnimationInterpolator(new FastOutLinearInInterpolator())
				//default max is 400dp
				.setMaxTextWidth(350f)
				.setOnHidePromptListener(----).create();
			mPrompt.show();

Also, for your reference, it also shows this log before crashing... totally missed seeing this before

 I/dalvikvm: Could not find method android.app.Activity.getColor, referenced from method uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.getColour
 W/dalvikvm: VFY: unable to resolve virtual method 136: Landroid/app/Activity;.getColor (I)I
 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
 I/dalvikvm: Could not find method android.graphics.drawable.Drawable.setTintList, referenced from method uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.create
 W/dalvikvm: VFY: unable to resolve virtual method 1386: Landroid/graphics/drawable/Drawable;.setTintList (Landroid/content/res/ColorStateList;)V
 D/dalvikvm: VFY: replacing opcode 0x6e at 0x00d0
 I/dalvikvm: Could not find method android.app.Activity.getDrawable, referenced from method uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.setIcon
W/dalvikvm: VFY: unable to resolve virtual method 139: Landroid/app/Activity;.getDrawable (I)Landroid/graphics/drawable/Drawable;
 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
 I/dalvikvm: Could not find method android.app.Activity.getColor, referenced from method uk.co.samuelwall.materialtaptargetprompt.MaterialTapTargetPrompt$Builder.setIconDrawableColourFilterFromRes
W/dalvikvm: VFY: unable to resolve virtual method 136: Landroid/app/Activity;.getColor (I)I

**Comment by sjwall** [comment]
With 1.8.3 exiting gracefully in the library it indicates that `findViewById(R.id.menu_next)` is returning null.
This means that `create()` will return null as the prompt does not have a valid target.

The extra log information is showing that the methods `Drawable.setTintList`, `Activity.getDrawable` and `Activity.getColor` cannot be found. These methods have been added to Android in Lollipop and Marshmallow. 
When running a device that is an older version of Android these "errors" will be shown by Android. But these aren't "errors" as the library checks what Android version it is running on to see if it can use them. The Android JVM will just ignore the fact that the methods don't exist because they aren't reachable in code. An example is below with `getColor` which was added to `Context` class in Marshmallow:

```java
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
            {
                colour = mActivity.getColor(id);
            }
            else
            {
                colour = mActivity.getResources().getColor(id);
            }
```

**Comment by chinmoyeedash** [comment]
No, view is not returning null(have debugged this) , also as i mentioned, same code works if i change only the gradle file to earlier version of MaterialTapTraget, but then I cannot target sdk 25

**Comment by sjwall** [comment]
I have investigated further and not been able to find anything :(
Could you provided the stacktrace now that the null pointer isn't occurring in the library please?
