### ISSUE TITLE
Syncing only crash

### ISSUE THREAD

**Issue by coolmyll** [sjwall/MaterialTapTargetPrompt#42]
Syncing the library and running the app without even inserting any code cause my app to crash on startup.

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.tea2code.e_gym, PID: 22205
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tea2code.e_gym/com.tea2code.e_gym.MainActivity}: android.view.InflateException: Binary XML file line #24: Binary XML file line #1: Error inflating class fragment
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6126)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: android.view.InflateException: Binary XML file line #24: Binary XML file line #1: Error inflating class fragment
                   Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class fragment
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTypeface(android.graphics.Typeface)' on a null object reference
                      at com.tea2code.e_gym.MainActivityFragment.onViewCreated(MainActivityFragment.java:31)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1264)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
                      at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1681)
                      at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3357)
                      at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                      at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:378)
                      at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
                      at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:964)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                      at com.tea2code.e_gym.MainActivity.onCreate(MainActivity.java:40)
                      at android.app.Activity.performCreate(Activity.java:6679)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6126)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

Unrelated crash. But it only happens when i sync the library.

**Comment by sjwall** [comment]
It is peculiar that this library is causing that. From the stack trace it looks like you are doing `textView.setTypeface(. . .)` where the text view is null. Have you tried temporary commenting out the view you are setting the typeface on and seeing if that reveals an underlying issue else where it might then link to this library?

**Comment by coolmyll** [comment]
Weird. It is now fixed without removing the setTypeface. Maybe it was just a cleanup issue. 
Thanks for the reply.
